version: '2'
networks:
  back:
  front:
services:
  php:
    build: .
    networks:
      - back
  db:
    image: mishamx/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - back
  nginx:
    build: ./docker/nginx
    environment:
      APP_HOST: php
    networks:
      - back
      - front
    ports:
      - '$NGINX_PORT:80'